Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -28,23 +28,26 @@ jobs:
         distribution: 'temurin'
         cache: maven
 
-    - name: Set custom Maven build directory
-      run: |
-          mkdir -p ${{ runner.temp }}/target
-          chmod -R u+w ${{ runner.temp }}/target
+    # - name: Set custom Maven build directory
+    #   run: |
+    #       mkdir -p ${{ runner.temp }}/target
+    #       chmod -R u+w ${{ runner.temp }}/target
 
     # - name: Build with Maven
     #   run: mvn clean test -DoutputDirectory=${{ runner.temp }}/target
     #   shell: bash
 
-    - name: Ensure clean-up of target directory
-      run: |
-          for i in {1..3}; do
-            rm -f target/jacoco.exec || echo "Failed to delete jacoco.exec, retrying in 5 seconds" && sleep 5;
-          done
+    # - name: Ensure clean-up of target directory
+    #   run: |
+    #       for i in {1..3}; do
+    #         rm -f target/jacoco.exec || echo "Failed to delete jacoco.exec, retrying in 5 seconds" && sleep 5;
+    #       done
     
+    # - name: Build with Maven
+    #   run: mvn -B package --file pom.xml
+
     - name: Build with Maven
-      run: mvn -B package --file pom.xml
+      run: mvn --batch-mode --update-snapshots verify
 
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
     # - name: Update dependency graph
